### ISSUE TITLE
Update to compile with latest cppjieba code?

### ISSUE THREAD

**Issue by zxteloiv** [yanyiwu/cppjieba-server#2]
Firstly thank you for providing such easy-to-use tool.

I tried to compile the code natively with the latest code from `cppjieba` repo, obtaining lots of undefined indentifier errors.

I guess it is because the `limonp` is updated while all `cppjieba` and `husky` sources distributed here can not adapt to it. But I found that both `cppjieba` and `husky` also have a copy of `limonp` codes in their repo.

Would it be better to organize these dependencies in git submodules? In that way `cppjieba-server` may catch up with the latest dependency codes easily, and get rid of copying the dependencies here and complicating the cmake build system.

In addition, I found that the `cppjieba` image on Docker Hub is automatic built from the `cppjieba` repo and contains the code of `cppjieba-server`. But I don't found any Dockerfile from either repo. Would the docker image be updated with the latest jieba codes, too?

Thanks very much!

**Comment by yanyiwu** [comment]
I am not familar with git submodule , can you do me a favor? A pull request is best.

发自我的 iPhone

**Comment by zxteloiv** [comment]
Thanks. I would try to resolve the `husky` and `cppjieba` dependencies and make this repo compile.
